export const themes = {
  pommes: {
    name: 'Pommes',
    swatch: '#d4a96a',
    bg:          '#fffdf7',
    surface:     '#f7edd8',
    border:      '#e8d5b0',
    borderStrong:'#3d2a0e',
    text:        '#3d2a0e',
    textSub:     '#8b6f47',
    textMuted:   '#c4a882',
    solidBg:     '#3d2a0e',
    solidText:   '#ffffff',
  },
  figma: {
    name: 'Figma',
    swatch: '#000000',
    bg:          '#ffffff',
    surface:     '#f8f8f8',
    border:      '#e8e8e8',
    borderStrong:'#000000',
    text:        '#000000',
    textSub:     '#999999',
    textMuted:   '#cccccc',
    solidBg:     '#000000',
    solidText:   '#ffffff',
  },
  pop: {
    name: 'Pop',
    swatch: '#FFD600',
    bg:          '#ffffff',
    surface:     '#fff9e6',
    border:      '#ffe066',
    borderStrong:'#FFD600',
    text:        '#1a1a1a',
    textSub:     '#888888',
    textMuted:   '#bbbbbb',
    solidBg:     '#FFD600',
    solidText:   '#1a1a1a',
  },
  mint: {
    name: 'Mint',
    swatch: '#3dbf8a',
    bg:          '#f5fffc',
    surface:     '#e8f8f2',
    border:      '#b5e8d5',
    borderStrong:'#3dbf8a',
    text:        '#1a3d2e',
    textSub:     '#5a9980',
    textMuted:   '#9ecfbb',
    solidBg:     '#3dbf8a',
    solidText:   '#ffffff',
  },
}

export const defaultThemeId = 'pommes'
