// src/themes.js
export const themes = {
  pastel: {
    name: 'Pastel',
    swatch: '#d8dbe1',
    bg:          '#f8f9fa',
    surface:     '#f0f1f3',
    tabBg:       '#e8eaed',
    border:      '#dde0e5',
    borderStrong:'#6b7280',
    text:        '#374151',
    textSub:     '#6b7280',
    textMuted:   '#9ca3af',
    solidBg:     '#ddd6fe',
    solidText:   '#000000',
    selectedBg:  '#6b7280',
    selectedText:'#ffffff',
    levelColors: {
      A1: { bg: '#ddd6fe', text: '#5b21b6' },
      A2: { bg: '#bae6fd', text: '#0369a1' },
      B1: { bg: '#d9f99d', text: '#4d7c0f' },
    },
    sceneColors: {
      '日常生活':          { bg: '#d4f0e8', text: '#1a7a5a' },
      '買い物':            { bg: '#e8d4f0', text: '#7a1a9a' },
      '仕事・職場':        { bg: '#d4e4f0', text: '#1a4a7a' },
      '観光・旅行':        { bg: '#d4eaf8', text: '#1a6a9a' },
      '交通・移動':        { bg: '#f5f0d4', text: '#7a6a1a' },
      'レストラン・カフェ': { bg: '#f5e8d4', text: '#8a5a1a' },
      '病院・緊急':        { bg: '#f5d4d4', text: '#9a1a1a' },
      '学校・勉強':        { bg: '#ddf0d4', text: '#2a7a1a' },
      '自己紹介':          { bg: '#f5d4e8', text: '#9a1a6a' },
    },
  },
  pommes: {
    name: 'Pommes',
    swatch: '#d4a96a',
    bg:          '#fffdf7',
    surface:     '#f7edd8',
    tabBg:       '#ede0c8',
    border:      '#e8d5b0',
    borderStrong:'#3d2a0e',
    text:        '#3d2a0e',
    textSub:     '#8b6f47',
    textMuted:   '#c4a882',
    solidBg:     '#3d2a0e',
    solidText:   '#ffffff',
  },
  pop: {
    name: 'Pop',
    swatch: '#FFD600',
    bg:          '#ffffff',
    surface:     '#fff9e6',
    tabBg:       '#fff0b3',
    border:      '#ffe066',
    borderStrong:'#FFD600',
    text:        '#1a1a1a',
    textSub:     '#888888',
    textMuted:   '#bbbbbb',
    solidBg:     '#FFD600',
    solidText:   '#1a1a1a',
  },
  mint: {
    name: 'Mint',
    swatch: '#3dbf8a',
    bg:          '#f5fffc',
    surface:     '#e8f8f2',
    tabBg:       '#d0f0e4',
    border:      '#b5e8d5',
    borderStrong:'#3dbf8a',
    text:        '#1a3d2e',
    textSub:     '#5a9980',
    textMuted:   '#9ecfbb',
    solidBg:     '#3dbf8a',
    solidText:   '#ffffff',
  },
}

export const defaultThemeId = 'pastel'
